name: Release
on:
  push:
    tags: [ "v[0-9]+.*" ]

permissions:
  contents: write

jobs:
  create-release:
    if: github.repository_owner == 'ririsoft'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          title: $version
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    if: github.repository_owner == 'ririsoft'
    needs:
      - create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Verify package can be published
        run: cargo publish --dry-run

      - name: Publish package to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
