name: Rust
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rust-ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy, llvm-tools-preview

      - name: Setup rust smart caching
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --no-deps -- -D warnings
      
      - name: Run cargo build
        run: cargo build

      - name: Cargo tests 
        run: cargo test

      - name: Setup cargo-llvm-cov
        run: cargo install cargo-llvm-cov

      - name: Run code coverage test
        run: |
          cargo llvm-cov test --fail-under-lines 90